# re-run `docker compose up --build --force-recreate` when you wanna test your code

services:
  web-stack:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      # You may need to change this to your system's serial port path, but don't commit that change since it's system-specific
      # Only edit the path to the left of the ":". The right side is effectively a "rename" operation of that path for the container
      - /dev/ttyUSB0:/dev/ttyUSB0
    ports:
      - 8000:8000
