# READ THIS:
# - re-run `docker compose up --build --force-recreate` when you wanna test your code
# - You may need to change the "source" path below to your system's serial port path, but
#   don't commit that change since it's system-specific. Also, ONLY CHANGE THE SOURCE, not
#   the "target:" path below.

networks:
  chessbot:

services:
  web-stack:
    container_name: chessbot-web-stack
    # image: ghcr.io/collinroboticsclub/chessbot-web-stack:latest
    build:
      context: ./web-stack
      dockerfile: ./Dockerfile
    privileged: true
    networks:
      - chessbot
    volumes:
      - type: bind
        source: /dev/ttyUSB0 # might need to change this
        target: /dev/ttyUSB0 # DO NOT CHANGE THIS ONE
    ports:
      - 8000:8000
    # restart: unless-stopped
  camera-processor:
    container_name: chessbot-camera-processor
    # image: ghcr.io/collinroboticsclub/chessbot-opencv:latest
    build:
      context: ./opencv
      dockerfile: ./Dockerfile
    privileged: true
    networks:
      - chessbot
    volumes:
      - type: bind
        source: /dev/video0 # might need to change this
        target: /dev/video0 # DO NOT CHANGE THIS ONE
    ports:
      - 8001:8000
    # restart: unless-stopped
